// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhqolzjvupmwizzbzntx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocW9semp2dXBtd2l6emJ6bnR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODczOTksImV4cCI6MjA2NDc2MzM5OX0.ejuR6RXq_OnMKEIU94_qsRApcQoa8hN5JJreRNO4HlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);